# Use postgres/example user/password credentials
version: '3.1'

services:

  postrgresql:
    image: postgres
    restart: always
    container_name: postgresDB
    network_mode: bridge
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: access_salecaruser
      POSTGRES_USER: salecaruser
      POSTGRES_DB: salecar
    ports:
      - 5432:5432