FROM ubuntu:23.04

RUN apt update && \
    apt install -y curl && \
    apt install -y net-tools && \
    apt install -y iputils-ping && \
    apt install -y iptables && \
    apt install -y ufw && \
    apt install -y wget && \
    apt clean